# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-01 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpnews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='channel_like',
            field=models.TextField(default=''),
        ),
    ]
